# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterDemo0929' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
  # Pods for FlutterDemo0929

  target 'FlutterDemo0929Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterDemo0929UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
